// <auto-generated />
using System;
using CarSales.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarSales.Web.Data.Migrations
{
    [DbContext(typeof(CarSalesDbContext))]
    [Migration("20230427113815_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarSales.Infrastructure.Data.Entities.Owner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Owners");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UserId = "b5fef437-f504-46d2-926d-3158e54e1932"
                        },
                        new
                        {
                            Id = 2,
                            UserId = "926bee86-8bbd-43f6-bc1c-9639d43531a4"
                        },
                        new
                        {
                            Id = 3,
                            UserId = "66ccb670-f0dd-4aa1-a83d-8b2a0003bb50"
                        });
                });

            modelBuilder.Entity("CarSales.Infrastructure.Data.Entities.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<decimal>("SalePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SalesmanId")
                        .HasColumnType("int");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("SalesmanId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Sales");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OwnerId = 1,
                            SalePrice = 20000m,
                            SalesmanId = 1,
                            VehicleId = 3
                        });
                });

            modelBuilder.Entity("CarSales.Infrastructure.Data.Entities.Salesman", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SalesmanRating")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Salesmen");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SalesmanRating = 3,
                            UserId = "66ccb670-f0dd-4aa1-a83d-8b2a0003bb50"
                        });
                });

            modelBuilder.Entity("CarSales.Infrastructure.Data.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Credits")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "cbed6d2a-e60a-49df-a6e3-982ccd980393",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "dc12dbbb-42f7-48c0-bd17-aa3d808871c8",
                            Credits = 0m,
                            Email = "Admin@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Admin",
                            LastName = "Test",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@GMAIL.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAECpc3SqcXtbqfReBdZnizPUNosHXbPi2NKN8W0iPHCXd+DSptxxnSambJ9B2HQCnUg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "dbab16d1-b529-4887-8e93-0ce3290e6db3",
                            TwoFactorEnabled = false,
                            UserName = "Admin"
                        },
                        new
                        {
                            Id = "b5fef437-f504-46d2-926d-3158e54e1932",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "147f514a-ae32-4a60-81ee-4e4756a7d9db",
                            Credits = 0m,
                            Email = "Owner@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Owner",
                            LastName = "Test",
                            LockoutEnabled = false,
                            NormalizedEmail = "OWNER@GMAIL.COM",
                            NormalizedUserName = "OWNER",
                            PasswordHash = "AQAAAAIAAYagAAAAEMakFTcWs4CyR9N4Eb1YfCZ4vW80LRpv6wyQl//A9E+GLCU1Akt/O7awG8b0UAtfcA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "69914115-32d3-450e-9b9e-a6a968dbaaf5",
                            TwoFactorEnabled = false,
                            UserName = "Owner"
                        },
                        new
                        {
                            Id = "926bee86-8bbd-43f6-bc1c-9639d43531a4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c398881f-46ed-4969-9aba-9d9c1a5cd452",
                            Credits = 0m,
                            Email = "Owner2@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Owner2",
                            LastName = "Test",
                            LockoutEnabled = false,
                            NormalizedEmail = "OWNER2@GMAIL.COM",
                            NormalizedUserName = "OWNER2",
                            PasswordHash = "AQAAAAIAAYagAAAAEKnKAQIk3Lo42B/sQ4QogM888d1/O8ZsyMO9ICxhdBCntdjfMYCA7LwtWjgTiJw9cw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ca3deeb2-f00a-471a-86a7-d8a0a2731cfe",
                            TwoFactorEnabled = false,
                            UserName = "Owner2"
                        },
                        new
                        {
                            Id = "66ccb670-f0dd-4aa1-a83d-8b2a0003bb50",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e7bf1dd9-235e-4449-830c-184d73081541",
                            Credits = 0m,
                            Email = "Salesman@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Salesman",
                            LastName = "Test",
                            LockoutEnabled = false,
                            NormalizedEmail = "SALESMAN@GMAIL.COM",
                            NormalizedUserName = "SALESMAN",
                            PasswordHash = "AQAAAAIAAYagAAAAEMTwAnR1nIURiTTgTY0L8Hh/cb5uKe21BsByf5+C0JQsRW+pKtIFRyJ31TwmBT/9iA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "859c9d1d-3f06-4846-bc73-611db8dbb07e",
                            TwoFactorEnabled = false,
                            UserName = "Salesman"
                        });
                });

            modelBuilder.Entity("CarSales.Infrastructure.Data.Entities.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("KilometersDriven")
                        .HasColumnType("float");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("SalesmanId")
                        .HasColumnType("int");

                    b.Property<double>("TopSpeed")
                        .HasColumnType("float");

                    b.Property<int>("VehicleRating")
                        .HasColumnType("int");

                    b.Property<int>("VehicleType")
                        .HasColumnType("int");

                    b.Property<int>("YearProduced")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("SalesmanId");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "BMW",
                            Description = "Fast car",
                            ImageUrl = "https://media.ed.edmunds-media.com/bmw/m5/2021/oem/2021_bmw_m5_sedan_base_fq_oem_8_815.jpg",
                            KilometersDriven = 0.0,
                            Model = "M5",
                            Price = 9000m,
                            SalesmanId = 1,
                            TopSpeed = 250.0,
                            VehicleRating = 3,
                            VehicleType = 1,
                            YearProduced = 2016
                        },
                        new
                        {
                            Id = 2,
                            Brand = "BMW",
                            Description = "Classic car",
                            KilometersDriven = 0.0,
                            Model = "M3",
                            Price = 5000m,
                            SalesmanId = 1,
                            TopSpeed = 240.0,
                            VehicleRating = 3,
                            VehicleType = 1,
                            YearProduced = 2004
                        },
                        new
                        {
                            Id = 3,
                            Brand = "BMW",
                            Description = "Popular car",
                            KilometersDriven = 2000.0,
                            Model = "X5",
                            OwnerId = 1,
                            Price = 18000m,
                            TopSpeed = 243.0,
                            VehicleRating = 4,
                            VehicleType = 1,
                            YearProduced = 2020
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityRole");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "cbed6d2a-e60a-49df-a6e3-982ccd980393",
                            RoleId = "dacb7d40-e742-435c-b131-145300f3c97d"
                        },
                        new
                        {
                            UserId = "b5fef437-f504-46d2-926d-3158e54e1932",
                            RoleId = "bbea2448-c801-43d1-8b05-e3a2c22338d9"
                        },
                        new
                        {
                            UserId = "926bee86-8bbd-43f6-bc1c-9639d43531a4",
                            RoleId = "bbea2448-c801-43d1-8b05-e3a2c22338d9"
                        },
                        new
                        {
                            UserId = "66ccb670-f0dd-4aa1-a83d-8b2a0003bb50",
                            RoleId = "bbea2448-c801-43d1-8b05-e3a2c22338d9"
                        },
                        new
                        {
                            UserId = "66ccb670-f0dd-4aa1-a83d-8b2a0003bb50",
                            RoleId = "c63016c0-e087-43dc-bb9c-a8958a05cbdd"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CarSales.Infrastructure.Data.Entities.Role", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityRole");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasDiscriminator().HasValue("Role");

                    b.HasData(
                        new
                        {
                            Id = "dacb7d40-e742-435c-b131-145300f3c97d",
                            ConcurrencyStamp = "dacb7d40-e742-435c-b131-145300f3c97d",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR",
                            Description = "Admin"
                        },
                        new
                        {
                            Id = "bbea2448-c801-43d1-8b05-e3a2c22338d9",
                            ConcurrencyStamp = "bbea2448-c801-43d1-8b05-e3a2c22338d9",
                            Name = "Owner",
                            NormalizedName = "OWNER",
                            Description = "Can buy cars."
                        },
                        new
                        {
                            Id = "c63016c0-e087-43dc-bb9c-a8958a05cbdd",
                            ConcurrencyStamp = "c63016c0-e087-43dc-bb9c-a8958a05cbdd",
                            Name = "Salesman",
                            NormalizedName = "SALESMAN",
                            Description = "Can buy and sell cars."
                        });
                });

            modelBuilder.Entity("CarSales.Infrastructure.Data.Entities.Owner", b =>
                {
                    b.HasOne("CarSales.Infrastructure.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CarSales.Infrastructure.Data.Entities.Sale", b =>
                {
                    b.HasOne("CarSales.Infrastructure.Data.Entities.Owner", "Owner")
                        .WithMany("Sales")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CarSales.Infrastructure.Data.Entities.Salesman", "Salesman")
                        .WithMany("Sales")
                        .HasForeignKey("SalesmanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CarSales.Infrastructure.Data.Entities.Vehicle", "Vehicle")
                        .WithMany("Sales")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("Salesman");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("CarSales.Infrastructure.Data.Entities.Salesman", b =>
                {
                    b.HasOne("CarSales.Infrastructure.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CarSales.Infrastructure.Data.Entities.Vehicle", b =>
                {
                    b.HasOne("CarSales.Infrastructure.Data.Entities.Owner", "Owner")
                        .WithMany("Vehicles")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CarSales.Infrastructure.Data.Entities.Salesman", "Salesman")
                        .WithMany("Vehicles")
                        .HasForeignKey("SalesmanId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Owner");

                    b.Navigation("Salesman");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CarSales.Infrastructure.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CarSales.Infrastructure.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarSales.Infrastructure.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CarSales.Infrastructure.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarSales.Infrastructure.Data.Entities.Owner", b =>
                {
                    b.Navigation("Sales");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("CarSales.Infrastructure.Data.Entities.Salesman", b =>
                {
                    b.Navigation("Sales");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("CarSales.Infrastructure.Data.Entities.Vehicle", b =>
                {
                    b.Navigation("Sales");
                });
#pragma warning restore 612, 618
        }
    }
}
