// <auto-generated />
using System;
using CarSales.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarSales.Web.Data.Migrations
{
    [DbContext(typeof(CarSalesDbContext))]
    [Migration("20230507123532_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarSales.Infrastructure.Data.Entities.Importer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ImporterRating")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Importers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImporterRating = 3,
                            IsActive = true,
                            UserId = "10933c11-ac2a-410d-b60a-8b1d97324975"
                        });
                });

            modelBuilder.Entity("CarSales.Infrastructure.Data.Entities.Owner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Owners");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UserId = "b5fef437-f504-46d2-926d-3158e54e1932"
                        },
                        new
                        {
                            Id = 2,
                            UserId = "926bee86-8bbd-43f6-bc1c-9639d43531a4"
                        },
                        new
                        {
                            Id = 3,
                            UserId = "66ccb670-f0dd-4aa1-a83d-8b2a0003bb50"
                        },
                        new
                        {
                            Id = 4,
                            UserId = "10933c11-ac2a-410d-b60a-8b1d97324975"
                        });
                });

            modelBuilder.Entity("CarSales.Infrastructure.Data.Entities.RoleRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("RoleRequests");
                });

            modelBuilder.Entity("CarSales.Infrastructure.Data.Entities.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ImporterId")
                        .HasColumnType("int");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("int");

                    b.Property<decimal>("SalePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("SalesmanId")
                        .HasColumnType("int");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ImporterId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("SalesmanId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Sales");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImporterId = 1,
                            SalePrice = 10000m,
                            SalesmanId = 1,
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 2,
                            OwnerId = 1,
                            SalePrice = 20000m,
                            SalesmanId = 1,
                            VehicleId = 3
                        });
                });

            modelBuilder.Entity("CarSales.Infrastructure.Data.Entities.Salesman", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("SalesmanRating")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Salesmen");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            SalesmanRating = 3,
                            UserId = "66ccb670-f0dd-4aa1-a83d-8b2a0003bb50"
                        });
                });

            modelBuilder.Entity("CarSales.Infrastructure.Data.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Credits")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "cbed6d2a-e60a-49df-a6e3-982ccd980393",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e5800921-d669-4a19-8684-b6d820f862c3",
                            Credits = 50000m,
                            Email = "Admin@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Admin",
                            LastName = "Test",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@GMAIL.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEIRPxvpnDmVHDUiE2SiQBqXg7YTuiqehX9ALj3wA30ksylBEUXhOHZO8y36vWfmNIw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "38fd7504-6459-4917-a1b0-5ba28f3723a1",
                            TwoFactorEnabled = false,
                            UserName = "Admin"
                        },
                        new
                        {
                            Id = "b5fef437-f504-46d2-926d-3158e54e1932",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fd1200a6-4703-4f43-816b-e11bd4faeb90",
                            Credits = 50000m,
                            Email = "Owner@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Owner",
                            LastName = "Test",
                            LockoutEnabled = false,
                            NormalizedEmail = "OWNER@GMAIL.COM",
                            NormalizedUserName = "OWNER",
                            PasswordHash = "AQAAAAIAAYagAAAAEPB31eUu9kzEu+yAB8vacbUNCcnfx3S+yQxEYC/ipfPIWDOYUJ2l8heby0CyXs/iYw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0cbb627c-b96b-4646-b352-7e3d30ff9a5e",
                            TwoFactorEnabled = false,
                            UserName = "Owner"
                        },
                        new
                        {
                            Id = "926bee86-8bbd-43f6-bc1c-9639d43531a4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4d7889f8-465c-4e46-b034-87f88d49df6a",
                            Credits = 50000m,
                            Email = "Owner2@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Owner2",
                            LastName = "Test",
                            LockoutEnabled = false,
                            NormalizedEmail = "OWNER2@GMAIL.COM",
                            NormalizedUserName = "OWNER2",
                            PasswordHash = "AQAAAAIAAYagAAAAEF2zgvlzxK/K+8qHnJRLdxgDT4FxgYajpvxbITzUG45Oa224YR+6PDkroDnkjwPBKg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a5418a4d-7f4d-432a-9b51-516fc3427e31",
                            TwoFactorEnabled = false,
                            UserName = "Owner2"
                        },
                        new
                        {
                            Id = "66ccb670-f0dd-4aa1-a83d-8b2a0003bb50",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5414a592-5134-4d1b-ac69-93eacd4b41f6",
                            Credits = 50000m,
                            Email = "Salesman@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Salesman",
                            LastName = "Test",
                            LockoutEnabled = false,
                            NormalizedEmail = "SALESMAN@GMAIL.COM",
                            NormalizedUserName = "SALESMAN",
                            PasswordHash = "AQAAAAIAAYagAAAAEKMHw7yjuJ+1Xi97spKUT/x6YnL3UBybrXTZhAXPJrkwj2lJWMBqenloBPtH8MHUcg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "82abc4c7-f8ab-4379-9fc4-85f70fafef2c",
                            TwoFactorEnabled = false,
                            UserName = "Salesman"
                        },
                        new
                        {
                            Id = "10933c11-ac2a-410d-b60a-8b1d97324975",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3886dee5-29f8-4cd9-86f2-f5b5a3a1cf9f",
                            Credits = 50000m,
                            Email = "Importer@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Importer",
                            LastName = "Test",
                            LockoutEnabled = false,
                            NormalizedEmail = "IMPORTER@GMAIL.COM",
                            NormalizedUserName = "IMPORTER",
                            PasswordHash = "AQAAAAIAAYagAAAAEIPJ0wcL7jOp2mUciQcdeGx+xwgC6p7SABmXlvSgVe9RWNBe/XCnP1jjoY/DnuXh2Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2aa13d60-98a1-4ce1-8e8e-b50bbf83bea3",
                            TwoFactorEnabled = false,
                            UserName = "Importer"
                        });
                });

            modelBuilder.Entity("CarSales.Infrastructure.Data.Entities.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ImporterId")
                        .HasColumnType("int");

                    b.Property<double>("KilometersDriven")
                        .HasColumnType("float");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("SalesmanId")
                        .HasColumnType("int");

                    b.Property<double>("TopSpeed")
                        .HasColumnType("float");

                    b.Property<int>("VehicleRating")
                        .HasColumnType("int");

                    b.Property<int>("VehicleType")
                        .HasColumnType("int");

                    b.Property<int>("YearProduced")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ImporterId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("SalesmanId");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "BMW",
                            Description = "Fast car",
                            ImageUrl = "https://media.ed.edmunds-media.com/bmw/m5/2021/oem/2021_bmw_m5_sedan_base_fq_oem_8_815.jpg",
                            KilometersDriven = 0.0,
                            Model = "M5",
                            Price = 9000m,
                            SalesmanId = 1,
                            TopSpeed = 250.0,
                            VehicleRating = 3,
                            VehicleType = 1,
                            YearProduced = 2016
                        },
                        new
                        {
                            Id = 2,
                            Brand = "BMW",
                            Description = "Classic car",
                            ImporterId = 1,
                            KilometersDriven = 0.0,
                            Model = "M3",
                            Price = 5000m,
                            TopSpeed = 240.0,
                            VehicleRating = 3,
                            VehicleType = 1,
                            YearProduced = 2004
                        },
                        new
                        {
                            Id = 3,
                            Brand = "BMW",
                            Description = "Popular car",
                            KilometersDriven = 2000.0,
                            Model = "X5",
                            OwnerId = 1,
                            Price = 18000m,
                            TopSpeed = 243.0,
                            VehicleRating = 4,
                            VehicleType = 1,
                            YearProduced = 2020
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityRole");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "cbed6d2a-e60a-49df-a6e3-982ccd980393",
                            RoleId = "dacb7d40-e742-435c-b131-145300f3c97d"
                        },
                        new
                        {
                            UserId = "b5fef437-f504-46d2-926d-3158e54e1932",
                            RoleId = "bbea2448-c801-43d1-8b05-e3a2c22338d9"
                        },
                        new
                        {
                            UserId = "926bee86-8bbd-43f6-bc1c-9639d43531a4",
                            RoleId = "bbea2448-c801-43d1-8b05-e3a2c22338d9"
                        },
                        new
                        {
                            UserId = "66ccb670-f0dd-4aa1-a83d-8b2a0003bb50",
                            RoleId = "bbea2448-c801-43d1-8b05-e3a2c22338d9"
                        },
                        new
                        {
                            UserId = "10933c11-ac2a-410d-b60a-8b1d97324975",
                            RoleId = "bbea2448-c801-43d1-8b05-e3a2c22338d9"
                        },
                        new
                        {
                            UserId = "66ccb670-f0dd-4aa1-a83d-8b2a0003bb50",
                            RoleId = "c63016c0-e087-43dc-bb9c-a8958a05cbdd"
                        },
                        new
                        {
                            UserId = "10933c11-ac2a-410d-b60a-8b1d97324975",
                            RoleId = "9cbd5531-0c49-4889-95b9-b81fc1e7653a"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CarSales.Infrastructure.Data.Entities.Role", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityRole");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasDiscriminator().HasValue("Role");

                    b.HasData(
                        new
                        {
                            Id = "dacb7d40-e742-435c-b131-145300f3c97d",
                            ConcurrencyStamp = "dacb7d40-e742-435c-b131-145300f3c97d",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR",
                            Description = "Admin"
                        },
                        new
                        {
                            Id = "bbea2448-c801-43d1-8b05-e3a2c22338d9",
                            ConcurrencyStamp = "bbea2448-c801-43d1-8b05-e3a2c22338d9",
                            Name = "Owner",
                            NormalizedName = "OWNER",
                            Description = "Can buy vehicles."
                        },
                        new
                        {
                            Id = "c63016c0-e087-43dc-bb9c-a8958a05cbdd",
                            ConcurrencyStamp = "c63016c0-e087-43dc-bb9c-a8958a05cbdd",
                            Name = "Salesman",
                            NormalizedName = "SALESMAN",
                            Description = "Can buy and sell vehicles."
                        },
                        new
                        {
                            Id = "9cbd5531-0c49-4889-95b9-b81fc1e7653a",
                            ConcurrencyStamp = "9cbd5531-0c49-4889-95b9-b81fc1e7653a",
                            Name = "Importer",
                            NormalizedName = "IMPORTER",
                            Description = "Imports vehicles."
                        });
                });

            modelBuilder.Entity("CarSales.Infrastructure.Data.Entities.Importer", b =>
                {
                    b.HasOne("CarSales.Infrastructure.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CarSales.Infrastructure.Data.Entities.Owner", b =>
                {
                    b.HasOne("CarSales.Infrastructure.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CarSales.Infrastructure.Data.Entities.RoleRequest", b =>
                {
                    b.HasOne("CarSales.Infrastructure.Data.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarSales.Infrastructure.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CarSales.Infrastructure.Data.Entities.Sale", b =>
                {
                    b.HasOne("CarSales.Infrastructure.Data.Entities.Importer", "Importer")
                        .WithMany()
                        .HasForeignKey("ImporterId");

                    b.HasOne("CarSales.Infrastructure.Data.Entities.Owner", "Owner")
                        .WithMany("Sales")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CarSales.Infrastructure.Data.Entities.Salesman", "Salesman")
                        .WithMany("Sales")
                        .HasForeignKey("SalesmanId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CarSales.Infrastructure.Data.Entities.Vehicle", "Vehicle")
                        .WithMany("Sales")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Importer");

                    b.Navigation("Owner");

                    b.Navigation("Salesman");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("CarSales.Infrastructure.Data.Entities.Salesman", b =>
                {
                    b.HasOne("CarSales.Infrastructure.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CarSales.Infrastructure.Data.Entities.Vehicle", b =>
                {
                    b.HasOne("CarSales.Infrastructure.Data.Entities.Importer", "Importer")
                        .WithMany("Vehicles")
                        .HasForeignKey("ImporterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CarSales.Infrastructure.Data.Entities.Owner", "Owner")
                        .WithMany("Vehicles")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CarSales.Infrastructure.Data.Entities.Salesman", "Salesman")
                        .WithMany("Vehicles")
                        .HasForeignKey("SalesmanId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Importer");

                    b.Navigation("Owner");

                    b.Navigation("Salesman");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CarSales.Infrastructure.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CarSales.Infrastructure.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarSales.Infrastructure.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CarSales.Infrastructure.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarSales.Infrastructure.Data.Entities.Importer", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("CarSales.Infrastructure.Data.Entities.Owner", b =>
                {
                    b.Navigation("Sales");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("CarSales.Infrastructure.Data.Entities.Salesman", b =>
                {
                    b.Navigation("Sales");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("CarSales.Infrastructure.Data.Entities.Vehicle", b =>
                {
                    b.Navigation("Sales");
                });
#pragma warning restore 612, 618
        }
    }
}
