// <auto-generated />
using System;
using CarSales.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarSales.Infrastructure.Data.Migrations
{
    [DbContext(typeof(CarSalesDbContext))]
    partial class CarSalesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarSales.Infrastructure.Data.Entities.Importer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ImporterRating")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Importers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImporterRating = 3,
                            IsActive = true,
                            UserId = "10933c11-ac2a-410d-b60a-8b1d97324975"
                        });
                });

            modelBuilder.Entity("CarSales.Infrastructure.Data.Entities.Offer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OfferorId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SalesmanId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OfferorId");

                    b.HasIndex("SalesmanId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Offers");
                });

            modelBuilder.Entity("CarSales.Infrastructure.Data.Entities.Owner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Owners");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UserId = "b5fef437-f504-46d2-926d-3158e54e1932"
                        },
                        new
                        {
                            Id = 2,
                            UserId = "926bee86-8bbd-43f6-bc1c-9639d43531a4"
                        },
                        new
                        {
                            Id = 3,
                            UserId = "66ccb670-f0dd-4aa1-a83d-8b2a0003bb50"
                        },
                        new
                        {
                            Id = 4,
                            UserId = "10933c11-ac2a-410d-b60a-8b1d97324975"
                        },
                        new
                        {
                            Id = 5,
                            UserId = "4d693871-c20b-4e9f-8490-1c641b9e3a40"
                        });
                });

            modelBuilder.Entity("CarSales.Infrastructure.Data.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Features")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Interior")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Longevity")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Overview")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Performance")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ReviewStatus")
                        .HasColumnType("int");

                    b.Property<int>("ReviewType")
                        .HasColumnType("int");

                    b.Property<int>("ReviewerId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReviewerId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Interior = "The M5 has an elegant leather interior with supportive sport seats. Unlike many of its rivals, BMW hasn't gone the all-touchscreen route, so adjusting the air conditioning or radio (via physical controls) is easy to do while the vehicle is in motion. The M5 comes with a slew of desirable features such as customizable ambient interior lighting, a heated steering wheel, heated front seats, and a power-adjustable steering column. BMW offers ventilated front seats with massage functionality, heated rear seats, and four-zone automatic climate control for more coin. As for storage space, the M5 has useful cubbies in the cabin, and its trunk held six carry-on suitcases in our testing.",
                            Overview = "Some cars are big-bodied and some are thrilling. The BMW M5 is both, with a body based on the regular 5-series and a heart-and-lung transplant courtesy of the brand's M performance division. Under the hood lives a spectacular 600-hp twin-turbo V-8 bolted to an eight-speed automatic transmission that powers all four wheels. An optional Competition package turns up the heat with 17 extra horsepower, a more soulful exhaust, stiffer suspension, and Competition badging and trim. That version rocketed to 60 mph in 2.8 seconds in our testing. Built to handle the rigors of mountain hairpins, blasts on the autobahn, and everyday life the M5 offers a premium experience with a penchant for fireworks. Unlike its closest competitor, the Cadillac CT5-V Blackwing, the Bimmer's stealthy packaging isn't offset by a thunderous exhaust but its impressive comfort and refinement make it among the best in the premium sports sedan segment.",
                            Performance = "The M5 is mighty, boasting 600 horsepower from its twin-turbo 4.4-liter V-8 in base form. In the more track-focused Competition, that figure increases to 617 horses. Believing that the Competition's V-8 had even more power than that we took that model to a dynamometer, were our suspicions proved true. We've also strapped our testing gear to both the regular M5 as well as the Competition model. Both met our expectations with brutally quick acceleration, sports-car-like cornering grip, and amazing stopping power. Likewise, the Competition proved to be quicker than the regular M5 on Virginia International Raceway's Grand Course at the 2019 Lightning Lap competition. Driving enjoyment is maximized here with lively and direct steering and a well-controlled albeit stiff ride. That doesn't mean the M5 can't also do duty as a luxury sedan: In Comfort mode, it cruises placidly, the cabin whisper quiet.",
                            Price = 150m,
                            ReviewStatus = 1,
                            ReviewType = 1,
                            ReviewerId = 1,
                            Title = "Rocket-ship propulsion, rear-drive mode adds spirit, luxe, comfy cabin.",
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 2,
                            Overview = "Driving a Bugatti Veyron is like carrying a 14.6-foot-long open wallet that is spewing 50-dollar bills. Drivers rush up from behind, tailgating before swerving into either of the Veyron’s rear-three-quarter blind spots, where they hang ape-like out of windows to snap photos with their cell phones. They won’t leave, either, because they know the Bugatti, averaging 11 mpg, can’t go far without refueling and that its driver will soon need to take a minute to compose himself. And when you open the Veyron’s door to exit—a gymnastic feat that requires grabbing one of your own ankles to drag it across that huge, hot sill—you will be greeted by 5 to 15 persons wielding cameras and asking questions. If you’re wearing shorts or a skirt, here’s a tip: Wear underwear.",
                            Performance = "The somewhat disappointing news is that despite accurate, nicely weighted steering and 1.00 g of skidpad grip, the car isn’t particularly nimble in the hills, where it is taxed by its 4486-pound heft. It feels more like a Benz SL63 AMG than, say, a BMW M3.\r\n\r\nThe Veyron’s weird shifter, which we named Klaatu, is as alien as the rest of the car. Push down for park. Push once to the right for drive. Twice to the right for sport mode. Left for neutral. Left and down for reverse. No matter where you shove it, it instantly returns to its original position, à la BMW turn signals. This is annoying, but resist the urge to abuse any gears. A new transmission costs $123,200. Speaking of abuse, within the 366-page hardcover owner’s manual, there are 190 boxed messages headlined “WARNING!”\r\n",
                            Price = 100m,
                            ReviewStatus = 1,
                            ReviewType = 0,
                            ReviewerId = 1,
                            Title = "Three good powertrain options, high-end cabin materials, cutting-edge infotainment tech.",
                            VehicleId = 2
                        },
                        new
                        {
                            Id = 3,
                            Features = "Audi offers an average standard warranty that when compared with other premium brands, looks pretty basic. Jaguar offers more value here, with longer warranties and five years of complimentary scheduled maintenance",
                            Interior = "The A6's interior design is sleek, modern, and nicely put together from excellent-quality materials. Soft leather adorns the seats and armrests, rich-looking wood and nickel-finished metal trim is tastefully applied to the dash and doors, and the majority of the A6's secondary controls—climate, drive mode, etc.—are handled by a large touch-sensitive panel underneath the main infotainment display. A similar system is used in the A8 luxury sedan and the Q8 crossover, and despite our usual griping about the takeover of touchscreen controls, it works well and provides satisfying haptic feedback. A large trunk and easy-to-fold rear seatbacks make the A6 great for hauling cargo. We fit six of our carry-on suitcases in the trunk, which ties both the E450 and the 540i. The Audi offered far more space than either of those two with the rear seats folded, managing to hold 20 cases; the Benz held 18 and the BMW 16.",
                            Longevity = "Audi offers quite a few standard and optional driver-assistance features, including a system that watches out for traffic to save you from stepping out of the car and into the path of a moving vehicle. For more information about the A6's crash-test results, visit the National Highway Traffic Safety Administration (NHTSA) and Insurance Institute for Highway Safety (IIHS) websites.",
                            Overview = "With its subdued styling and straightforward-but-refined interior, the 2024 Audi A6 is a classic German luxury sedan. There's nothing garish or overtly flashy about its design, and its comfort-first demeanor means it's perfect for long-haul autobahn runs. Entry-level models are powered by a turbocharged four-cylinder, but we like the optional turbocharged V-6 which makes a potent 335 horsepower. The more powerful S6 model (reviewed separately) livens things up with 444 horsepower and a tauter suspension. Driving enthusiasts may want to go with the S6 for more on-road entertainment, but those seeking quiet luxury will find that in the A6. Rivals such as the BMW 5-series, the Genesis G80, and the Mercedes-Benz E-Classserve as natural comparisons to the Audi and all offer similar style, comfort, and quality.",
                            Performance = "The A6's two powertrains—a 261-hp turbocharged 2.0-liter four-cylinder and a 335-hp turbocharged 3.0-liter V-6—are both more than enough to haul this mid-size sedan around town without undue strain. Both powertrains employ hybrid technology with a 12- or 48-volt starter/alternator that runs the engine's stop-start system and other ancillary equipment. A seven-speed automatic transmission and Quattro all-wheel drive are both standard. The V-6 delivers plenty of thrust for merging and passing on the highway: at our test track, it charged from zero to 60 mph in just 4.8 seconds. Despite this quick result, it's not quite enough to outrun its key rivals, the BMW 540i xDrive and the Mercedes-Benz E450 4Matic. The 540i managed a 4.5-second run, while the Benz did it in 4.6. Thanks to its absorbent ride the A6 performs better as a luxury car than a sports sedan. We enjoyed its balanced handling and precise steering but never felt totally engaged when attacking twisty sections of road.",
                            Price = 200m,
                            ReviewStatus = 1,
                            ReviewType = 2,
                            ReviewerId = 1,
                            Title = "Impeccable interior furnishings, high-tech features integrated throughout, two perky turbo engine choices.",
                            VehicleId = 3
                        });
                });

            modelBuilder.Entity("CarSales.Infrastructure.Data.Entities.Reviewer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("PremiumReviewPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ShortReviewPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StandartReviewPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Reviewers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            PremiumReviewPrice = 200m,
                            ShortReviewPrice = 100m,
                            StandartReviewPrice = 150m,
                            UserId = "4d693871-c20b-4e9f-8490-1c641b9e3a40"
                        });
                });

            modelBuilder.Entity("CarSales.Infrastructure.Data.Entities.RoleRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("RoleRequests");
                });

            modelBuilder.Entity("CarSales.Infrastructure.Data.Entities.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ImporterId")
                        .HasColumnType("int");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("int");

                    b.Property<decimal>("SalePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("SalesmanId")
                        .HasColumnType("int");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ImporterId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("SalesmanId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Sales");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImporterId = 1,
                            SalePrice = 10000m,
                            SalesmanId = 1,
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 2,
                            OwnerId = 1,
                            SalePrice = 20000m,
                            SalesmanId = 1,
                            VehicleId = 3
                        });
                });

            modelBuilder.Entity("CarSales.Infrastructure.Data.Entities.Salesman", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("SalesmanRating")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Salesmen");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            SalesmanRating = 3,
                            UserId = "66ccb670-f0dd-4aa1-a83d-8b2a0003bb50"
                        });
                });

            modelBuilder.Entity("CarSales.Infrastructure.Data.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Credits")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "cbed6d2a-e60a-49df-a6e3-982ccd980393",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "164a826c-de21-4f2c-b173-21e5016c14db",
                            Credits = 50000m,
                            Email = "Admin@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Admin",
                            LastName = "Test",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@GMAIL.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEG2UJr8gZNyhBjFK2hM5SCoT7zrTJIluWAlxw/7T6a/guf6Ud+3OAVPfO0SQK1r3MA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "bf7629ba-ea3b-43ea-9df8-f94d1c33c422",
                            TwoFactorEnabled = false,
                            UserName = "Admin"
                        },
                        new
                        {
                            Id = "b5fef437-f504-46d2-926d-3158e54e1932",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e8ec5c31-5d0a-4538-be9e-c0f0261d5bb8",
                            Credits = 50000m,
                            Email = "Owner@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Owner",
                            LastName = "Test",
                            LockoutEnabled = false,
                            NormalizedEmail = "OWNER@GMAIL.COM",
                            NormalizedUserName = "OWNER",
                            PasswordHash = "AQAAAAIAAYagAAAAECnuYxQV9hWcfMcs6FZQvONsUQgB7nkh4p4O93O9r3xzUEk05FREvCPt3R6+iNI+wg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "505aba56-dad1-46ef-a204-ee6ae50ec050",
                            TwoFactorEnabled = false,
                            UserName = "Owner"
                        },
                        new
                        {
                            Id = "926bee86-8bbd-43f6-bc1c-9639d43531a4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "da568e35-4529-4f01-9250-d5b893b5af5f",
                            Credits = 50000m,
                            Email = "Owner2@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Owner2",
                            LastName = "Test",
                            LockoutEnabled = false,
                            NormalizedEmail = "OWNER2@GMAIL.COM",
                            NormalizedUserName = "OWNER2",
                            PasswordHash = "AQAAAAIAAYagAAAAEIQOEhF2Msv/3Ngr+1TQ8bbTEBxqunFlqPLKsDw1z3SpOOK9EUWVkyu7M55vgtKiyA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "1b0bc459-b842-40dc-9783-7d0cc9b85831",
                            TwoFactorEnabled = false,
                            UserName = "Owner2"
                        },
                        new
                        {
                            Id = "66ccb670-f0dd-4aa1-a83d-8b2a0003bb50",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "45c36068-61c0-4d7e-ba79-0bfd72d07f3f",
                            Credits = 50000m,
                            Email = "Salesman@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Salesman",
                            LastName = "Test",
                            LockoutEnabled = false,
                            NormalizedEmail = "SALESMAN@GMAIL.COM",
                            NormalizedUserName = "SALESMAN",
                            PasswordHash = "AQAAAAIAAYagAAAAECLg5yUQhOGIWgWjneF2/W+ogOpweAxOVKiwnB1vDvoYFHJ0dB0CcngQc6zeHNC2KQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "737f79ce-1fd4-4468-a5e0-8dcefbc1e11f",
                            TwoFactorEnabled = false,
                            UserName = "Salesman"
                        },
                        new
                        {
                            Id = "10933c11-ac2a-410d-b60a-8b1d97324975",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "998884f7-106b-44be-b02d-0dc630c6cee9",
                            Credits = 50000m,
                            Email = "Importer@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Importer",
                            LastName = "Test",
                            LockoutEnabled = false,
                            NormalizedEmail = "IMPORTER@GMAIL.COM",
                            NormalizedUserName = "IMPORTER",
                            PasswordHash = "AQAAAAIAAYagAAAAEFe7GWBAekh7fmEKLFv1AoBRlgxoF8xIJk/YTk0yu/t/5HNOSfsT4KBaN8qMrFsETg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "268f943c-16af-4eeb-b1b9-ff649ffbac9a",
                            TwoFactorEnabled = false,
                            UserName = "Importer"
                        },
                        new
                        {
                            Id = "4d693871-c20b-4e9f-8490-1c641b9e3a40",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ae32b112-70b9-4f61-8b51-1326e9b7bd08",
                            Credits = 50000m,
                            Email = "Reviewer@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Reviewer",
                            LastName = "Test",
                            LockoutEnabled = false,
                            NormalizedEmail = "REVIEWER@GMAIL.COM",
                            NormalizedUserName = "REVIEWER",
                            PasswordHash = "AQAAAAIAAYagAAAAEJa1legkw6pwzx0sEPP53W1MoBAjDCclacvg9q2Dn7lAMoDfWKJ5vUhSwXDi5iO6ZQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "dcf8fb61-6c17-4298-aabd-aca6a4394da1",
                            TwoFactorEnabled = false,
                            UserName = "Reviewer"
                        });
                });

            modelBuilder.Entity("CarSales.Infrastructure.Data.Entities.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ImporterId")
                        .HasColumnType("int");

                    b.Property<double>("KilometersDriven")
                        .HasColumnType("float");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("SalesmanId")
                        .HasColumnType("int");

                    b.Property<double>("TopSpeed")
                        .HasColumnType("float");

                    b.Property<int>("VehicleRating")
                        .HasColumnType("int");

                    b.Property<int>("VehicleType")
                        .HasColumnType("int");

                    b.Property<int>("YearProduced")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ImporterId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("SalesmanId");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "BMW",
                            Description = "Fast car",
                            ImageUrl = "https://media.ed.edmunds-media.com/bmw/m5/2021/oem/2021_bmw_m5_sedan_base_fq_oem_8_815.jpg",
                            KilometersDriven = 0.0,
                            Model = "M5",
                            Price = 9000m,
                            SalesmanId = 1,
                            TopSpeed = 250.0,
                            VehicleRating = 3,
                            VehicleType = 1,
                            YearProduced = 2016
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Bugatti",
                            Description = "Fast sports car",
                            ImageUrl = "https://i.ytimg.com/vi/rvn4lHrr6AQ/maxresdefault.jpg",
                            KilometersDriven = 0.0,
                            Model = "Veyron",
                            Price = 30000m,
                            SalesmanId = 1,
                            TopSpeed = 350.0,
                            VehicleRating = 4,
                            VehicleType = 1,
                            YearProduced = 2011
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Audi",
                            Description = "Fast modern car",
                            ImageUrl = "https://cache1.24chasa.bg/Images/Cache/889/IMAGE_13981889_40_0.jpg",
                            KilometersDriven = 0.0,
                            Model = "A6",
                            Price = 20000m,
                            SalesmanId = 1,
                            TopSpeed = 300.0,
                            VehicleRating = 4,
                            VehicleType = 1,
                            YearProduced = 2014
                        },
                        new
                        {
                            Id = 4,
                            Brand = "BMW",
                            Description = "Fast modern car",
                            ImageUrl = "https://media.ed.edmunds-media.com/bmw/m3/2022/oem/2022_bmw_m3_sedan_competition_fq_oem_1_1600.jpg",
                            ImporterId = 1,
                            KilometersDriven = 0.0,
                            Model = "M3",
                            Price = 10000m,
                            TopSpeed = 240.0,
                            VehicleRating = 3,
                            VehicleType = 1,
                            YearProduced = 2004
                        },
                        new
                        {
                            Id = 5,
                            Brand = "BMW",
                            Description = "Popular car",
                            ImageUrl = "https://media.ed.edmunds-media.com/bmw/x5/2024/oem/2024_bmw_x5_4dr-suv_xdrive50e_fq_oem_1_1600.jpg",
                            KilometersDriven = 2000.0,
                            Model = "X5",
                            OwnerId = 1,
                            Price = 18000m,
                            TopSpeed = 243.0,
                            VehicleRating = 4,
                            VehicleType = 1,
                            YearProduced = 2020
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityRole");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "cbed6d2a-e60a-49df-a6e3-982ccd980393",
                            RoleId = "dacb7d40-e742-435c-b131-145300f3c97d"
                        },
                        new
                        {
                            UserId = "b5fef437-f504-46d2-926d-3158e54e1932",
                            RoleId = "bbea2448-c801-43d1-8b05-e3a2c22338d9"
                        },
                        new
                        {
                            UserId = "926bee86-8bbd-43f6-bc1c-9639d43531a4",
                            RoleId = "bbea2448-c801-43d1-8b05-e3a2c22338d9"
                        },
                        new
                        {
                            UserId = "66ccb670-f0dd-4aa1-a83d-8b2a0003bb50",
                            RoleId = "bbea2448-c801-43d1-8b05-e3a2c22338d9"
                        },
                        new
                        {
                            UserId = "10933c11-ac2a-410d-b60a-8b1d97324975",
                            RoleId = "bbea2448-c801-43d1-8b05-e3a2c22338d9"
                        },
                        new
                        {
                            UserId = "4d693871-c20b-4e9f-8490-1c641b9e3a40",
                            RoleId = "bbea2448-c801-43d1-8b05-e3a2c22338d9"
                        },
                        new
                        {
                            UserId = "66ccb670-f0dd-4aa1-a83d-8b2a0003bb50",
                            RoleId = "c63016c0-e087-43dc-bb9c-a8958a05cbdd"
                        },
                        new
                        {
                            UserId = "10933c11-ac2a-410d-b60a-8b1d97324975",
                            RoleId = "9cbd5531-0c49-4889-95b9-b81fc1e7653a"
                        },
                        new
                        {
                            UserId = "4d693871-c20b-4e9f-8490-1c641b9e3a40",
                            RoleId = "2d1b88f7-208a-43de-bb14-aca56b43080c"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CarSales.Infrastructure.Data.Entities.Role", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityRole");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasDiscriminator().HasValue("Role");

                    b.HasData(
                        new
                        {
                            Id = "dacb7d40-e742-435c-b131-145300f3c97d",
                            ConcurrencyStamp = "dacb7d40-e742-435c-b131-145300f3c97d",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR",
                            Description = "Admin"
                        },
                        new
                        {
                            Id = "bbea2448-c801-43d1-8b05-e3a2c22338d9",
                            ConcurrencyStamp = "bbea2448-c801-43d1-8b05-e3a2c22338d9",
                            Name = "Owner",
                            NormalizedName = "OWNER",
                            Description = "Can buy vehicles."
                        },
                        new
                        {
                            Id = "c63016c0-e087-43dc-bb9c-a8958a05cbdd",
                            ConcurrencyStamp = "c63016c0-e087-43dc-bb9c-a8958a05cbdd",
                            Name = "Salesman",
                            NormalizedName = "SALESMAN",
                            Description = "Can buy and sell vehicles."
                        },
                        new
                        {
                            Id = "9cbd5531-0c49-4889-95b9-b81fc1e7653a",
                            ConcurrencyStamp = "9cbd5531-0c49-4889-95b9-b81fc1e7653a",
                            Name = "Importer",
                            NormalizedName = "IMPORTER",
                            Description = "Can buy and import vehicles."
                        },
                        new
                        {
                            Id = "2d1b88f7-208a-43de-bb14-aca56b43080c",
                            ConcurrencyStamp = "2d1b88f7-208a-43de-bb14-aca56b43080c",
                            Name = "Reviewer",
                            NormalizedName = "REVIEWER",
                            Description = "Can buy and review vehicles."
                        });
                });

            modelBuilder.Entity("CarSales.Infrastructure.Data.Entities.Importer", b =>
                {
                    b.HasOne("CarSales.Infrastructure.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CarSales.Infrastructure.Data.Entities.Offer", b =>
                {
                    b.HasOne("CarSales.Infrastructure.Data.Entities.Owner", "Offeror")
                        .WithMany("Offers")
                        .HasForeignKey("OfferorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CarSales.Infrastructure.Data.Entities.Salesman", "Salesman")
                        .WithMany("Offers")
                        .HasForeignKey("SalesmanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CarSales.Infrastructure.Data.Entities.Vehicle", "Vehicle")
                        .WithMany("Offers")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Offeror");

                    b.Navigation("Salesman");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("CarSales.Infrastructure.Data.Entities.Owner", b =>
                {
                    b.HasOne("CarSales.Infrastructure.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CarSales.Infrastructure.Data.Entities.Review", b =>
                {
                    b.HasOne("CarSales.Infrastructure.Data.Entities.Reviewer", "Reviewer")
                        .WithMany("Reviews")
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarSales.Infrastructure.Data.Entities.Vehicle", "Vehicle")
                        .WithMany("Reviews")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reviewer");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("CarSales.Infrastructure.Data.Entities.Reviewer", b =>
                {
                    b.HasOne("CarSales.Infrastructure.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CarSales.Infrastructure.Data.Entities.RoleRequest", b =>
                {
                    b.HasOne("CarSales.Infrastructure.Data.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarSales.Infrastructure.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CarSales.Infrastructure.Data.Entities.Sale", b =>
                {
                    b.HasOne("CarSales.Infrastructure.Data.Entities.Importer", "Importer")
                        .WithMany()
                        .HasForeignKey("ImporterId");

                    b.HasOne("CarSales.Infrastructure.Data.Entities.Owner", "Owner")
                        .WithMany("Sales")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CarSales.Infrastructure.Data.Entities.Salesman", "Salesman")
                        .WithMany("Sales")
                        .HasForeignKey("SalesmanId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CarSales.Infrastructure.Data.Entities.Vehicle", "Vehicle")
                        .WithMany("Sales")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Importer");

                    b.Navigation("Owner");

                    b.Navigation("Salesman");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("CarSales.Infrastructure.Data.Entities.Salesman", b =>
                {
                    b.HasOne("CarSales.Infrastructure.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CarSales.Infrastructure.Data.Entities.Vehicle", b =>
                {
                    b.HasOne("CarSales.Infrastructure.Data.Entities.Importer", "Importer")
                        .WithMany("Vehicles")
                        .HasForeignKey("ImporterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CarSales.Infrastructure.Data.Entities.Owner", "Owner")
                        .WithMany("Vehicles")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CarSales.Infrastructure.Data.Entities.Salesman", "Salesman")
                        .WithMany("Vehicles")
                        .HasForeignKey("SalesmanId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Importer");

                    b.Navigation("Owner");

                    b.Navigation("Salesman");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CarSales.Infrastructure.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CarSales.Infrastructure.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarSales.Infrastructure.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CarSales.Infrastructure.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarSales.Infrastructure.Data.Entities.Importer", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("CarSales.Infrastructure.Data.Entities.Owner", b =>
                {
                    b.Navigation("Offers");

                    b.Navigation("Sales");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("CarSales.Infrastructure.Data.Entities.Reviewer", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("CarSales.Infrastructure.Data.Entities.Salesman", b =>
                {
                    b.Navigation("Offers");

                    b.Navigation("Sales");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("CarSales.Infrastructure.Data.Entities.Vehicle", b =>
                {
                    b.Navigation("Offers");

                    b.Navigation("Reviews");

                    b.Navigation("Sales");
                });
#pragma warning restore 612, 618
        }
    }
}
